#!/usr/bin/env python

from __future__ import print_function

import os,sys
import argparse
import csv

parser = argparse.ArgumentParser(description='Convert CSV file to TeX tabular format.')
parser.add_argument('filename', type=str, help='filename or path to the csv file')

def main(filename):
    if not os.path.exists(filename):
        print("FileNotFoundException: {0} is not found.".format(filename))
        sys.exit(1)
    _, ext = os.path.splitext(os.path.basename(filename))
    if ext != ".csv":
        print("Target file must be csv file.")
        sys.exit(1)
    with open(filename, 'r') as f:
        reader = csv.reader(f)
        print("\\begin{table}[htb]")
        print("\t\\begin{center}")
        print("\t\t\\caption{ここにタイトルを入れてね}")
        print("\t\t\\begin{tabular}{", end='')
        col_len = len(next(reader))
        for i in range(0, col_len):
            print("c", end='')
            if i != col_len-1:
                print("|", end='')
        print("} \\hline \\hline")
        f.seek(0) # go back to entry point of reader
        header = next(reader)
        print("\t\t\t", end='')
        for index, key in enumerate(header):
            print("{0} ".format(key), end='')
            if index == len(header)-1:
                print("\\\\ \\hline")
            else:
                print("& ", end='')
        for row in reader:
            print("\t\t\t", end='')
            for index, key in enumerate(row):
                print("{0} ".format(key), end='')
                if index == len(row)-1:
                    print("\\\\ \\hline")
                else:
                    print("& ", end='')
        print("\t\t\\end{tabular}")
        print("\t\\end{center}")
        print("\\end{table}")

if __name__ == '__main__':
    args = parser.parse_args()
    main(args.filename)
