#!/usr/bin/env python

from __future__ import print_function

import os,sys
import argparse

parser = argparse.ArgumentParser(description='Print Full Path to the file.')
parser.add_argument('filename', type=str, help='filename or path to the file')

def main(filename):
    if not os.path.exists(filename):
        raise IOError
    print(os.path.abspath(filename))

if __name__ == '__main__':
    args = parser.parse_args()
    main(args.filename)
